price = input('Price of the product = ')
discount = input('Discount in % = ')
price = float(price)
discount = float(discount)
discount_value = round((discount/100)*price, 2)
discounted_price = round(price-discount_value, 2)
print(f'Initial price - {price}')
print(f'Discount in % - {discount}')
print(f'Price after discount - {discounted_price}')
print(f'value of discount - {discount_value}')
